[package]
name = "sputnik_gui"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "sputnik"
path = "src/main.rs"

[dependencies]
rfd = "0.17.2"
ropey = "1.6.1"
smol_str = "0.2"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.iced]
workspace = true
features = ["canvas", "advanced", "image", "tokio"]

[dependencies.sputnik_editor]
path = "../sputnik_editor"

[dependencies.anyhow]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tokio]
workspace = true
features = ["fs", "rt", "macros"]

[build-dependencies.winresource]
version = "0.1"

[dev-dependencies.iced_test]
workspace = true
