[package]
name = "sputnik_gui"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "sputnik"
path = "src/main.rs"

[dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
features = ["canvas", "advanced", "image"]

[dependencies.anyhow]
workspace = true

[dependencies.tracing]
workspace = true

[build-dependencies.winresource]
version = "0.1"
