[package]
name = "sputnik_gui"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "sputnik"
path = "src/main.rs"

[dependencies]
ropey = "1.6.1"
smol_str = "0.2"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
rev = "d7f5627a7581e92e4c928f7f1a180061dc6c7eb5"
features = ["canvas", "advanced", "image", "tokio"]

[dependencies.cosmic-text]
version = "0.19"

[dependencies.anyhow]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tokio]
workspace = true
features = ["fs", "rt", "macros"]

[build-dependencies.winresource]
version = "0.1"

[dev-dependencies.iced_test]
git = "https://github.com/iced-rs/iced.git"
rev = "d7f5627a7581e92e4c928f7f1a180061dc6c7eb5"
