[workspace]
members = ["sputnik_gui", "sputnik_editor"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["krozzzis"]
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package.sputnik_editor]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 2
lto = false
codegen-units = 16
panic = "unwind"
strip = false

[profile.production]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
debug = false

[workspace.dependencies.tracing]
version = "0.1"

[workspace.dependencies.anyhow]
version = "1.0"

[workspace.dependencies.tokio]
version = "1"

[workspace.dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
rev = "d7f5627a7581e92e4c928f7f1a180061dc6c7eb5"

[workspace.dependencies.iced_test]
git = "https://github.com/iced-rs/iced.git"
rev = "d7f5627a7581e92e4c928f7f1a180061dc6c7eb5"

[workspace.dependencies.cosmic-text]
version = "0.19"
